### ISSUE TITLE
Update FAB color to primary color

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1143]
- [x] Create color mixins
- [x] Call color mixin from stylesheet, with primary color
- [x] Update README to document color mixins
- [ ] Delete --plain modifier
- [ ] Include "breaking change" message about removing modifiers, point to color mixin as deprecation replacement.
