### ISSUE TITLE
Update switch color to secondary color

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1144]
- [ ] Create color mixins
- [ ] Call color mixin from stylesheet, with primary color
- [ ] Update README to document color mixins
