### ISSUE TITLE
Add Sass color mixin to drawer

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1145]
- [ ] Create color mixins
- [ ] Call color mixin from stylesheet, with primary color
- [ ] Update README to document color mixins

**Comment by acdvorak** [comment]
Duplicate of #943
