### ISSUE TITLE
Add Sass color mixin to slider

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1151]
- [x] Create color mixins
- [x] Call color mixin from stylesheet, with primary color
- [x] Delete any —primary --accent modifiers
- [x] Update README to document color mixins
- [x] Include "breaking change" message about removing modifiers, point to color mixin as deprecation replacement.
