### ISSUE TITLE
Investigate future test infrastructure

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#143]
Continued from #5 

- [x] Determine what type of mocha interface we want to use. The Qunit-style interface looks most similar to what we already have.
- [x] Decide on setup for running mocha locally 
- [x] Investigate what it would take to refactor all tests. Investigate potentially using something like recast.
- [ ] Ensure that Cross-Browser testing via Sauce Labs works and is less flaky
- [x] Ensure that debugging still works in development, and coverage still works on single runs / CI.
- [x] Ensure that all docs regarding testing are updated
