### ISSUE TITLE
Getting Started Documentation / SASS Mixins

### ISSUE THREAD

**Issue by MrChriZ** [material-components/material-components-web#1604]
The SASS Mixins section in the getting started documentation feels a bit strange.
Whilst I understand that it's trying to show the flexability of using SASS Mixins with MDC it doesn't fit with the tutorial at hand to create a simple greeting app - which isn't using SASS and won't have an SCSS file.

**Comment by kfranqueiro** [comment]
Thanks for pointing this out. We definitely plan to look at the getting started guide more closely in the context of theming and Sass use once we've done more theming work across our components.

**Comment by lynnjepsen** [comment]
Based on some research we did with MDC Web clients, we think the getting started documentation should cover:

- [ ] How to install the Node module for a single component
- [ ] How to setup webpack, including the sass-loader configuration
- [ ] How to call a Sass mixin, in order to customize that single component, and have it work with sass-loader
- [ ] How to use the vanilla implementation of a component which has JavaScript, and have it work with webpack and ES2015 modules
