### ISSUE TITLE
Add Sass color mixins to list

### ISSUE THREAD

**Issue by acdvorak** [material-components/material-components-web#1662]
- [x] Create color mixins
- [x] Call color mixins from baseline stylesheet
- [x] Add `--selected` modifier for `mdc-list-item` (using primary color)
- [x] Update README to document color mixins
