### ISSUE TITLE
Implement hover state for ripple

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#194]
Design has new motion patterns for ink ripples on hover for flat surfaces. Thus,

- [ ] Ripples need to be configurable such that they can either be shown or not shown when a surface is hovered over (both for css-only and JS ripple)
- [ ] The hover UX needs to be implemented
- [ ] Components with elevation that use ripples need to not show an ink wash on hover, but change elevation instead

**Comment by traviskaufman** [comment]
Q's needing answered:

- Which components need do _not_ receive ink wash on hover
- For components that need an elevation change, is that duration / curve always constant or does it depend on the shape and dimension of the surface?

**Comment by kfranqueiro** [comment]
Current design direction no longer calls for ripple on hover under any circumstances, so I'm closing this as obsolete.
