### ISSUE TITLE
Create simple Button screenshot HTML/CSS

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1995]
- [ ] Create a new simpler webpack.config.js in test/screenshot
- [ ] Screenshot HTML/CSS for button
- [ ] Ability to "run" webpack locally and view the HTML/CSS for button screenshot test

Note that there is no actual "test" yet. This is just setting up a sever
