### ISSUE TITLE
Push simple Button screenshot HTML/CSS to GCP

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1996]
- [ ] Setup GCP first!
- [ ] Create a script that runs screenshot testing suite by talking to CrossBrowserTesting.com
- [ ] Create the first screenshot test for button
- [ ] Instructions (in PR description) on how to run this test suite
