### ISSUE TITLE
Run a Button screenshot test from the command line

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#1999]
- [ ] Create an npm command that runs screenshot testing suite by talking to CrossBrowserTesting.com
- [ ] Create the first screenshot test for button
- [ ] Instructions (in PR description) on how to run this test suite
