### ISSUE TITLE
Baseline chip and chip set

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2003]
- [ ] `mdc-chip`
- [ ] use `mdc-states` within `mdc-chip`
- [ ] `mdc-chip__text`
- [ ] `mdc-chip-set`
- [ ] create foundation/adapter for basic chip functionality
