### ISSUE TITLE
Sass mixins to customize mdc-chip

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2004]
- [ ] `mdc-chip-border-radius`
- [ ] `mdc-chip-fill-color`
- [ ] `mdc-chip-ink-color`
- [ ] `mdc-chip-stroke-color`
