### ISSUE TITLE
Add mdc-chip__icon to mdc-chip

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2005]
- [ ] Handle leading icon cases
- [ ] Plan for future case of a check icon for the filter chip set
- [ ] Handle trailing icon cases
- [ ] Plan for future case of a close icon for the entry chip set
