### ISSUE TITLE
mdc-chip-set--choice

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2008]
- [ ] Add a new variant to `mdc-chip-set` called `mdc-chip-set--choice`
- [ ] Use mdc-states mixins  on `mdc-chip` for selected/activated state
- [ ] modify JS for single-select behavior
