### ISSUE TITLE
mdc-chip-set--filter

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2009]
- [x] new variant of `mdc-chip-set` called `mdc-chip-set--filter`
- [x] add multi-select behavior
- [ ] add a checkmark icon to the `mdc-chip`
- [ ] replace a leading-icon with a checkmark icon when the chip is selected
