### ISSUE TITLE
Publish a Node module for @material/webpack

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2214]
- [ ] Export CopyrightBannerPlugin
- [ ] Export PluginFactory (with method to createCssExtractionPlugin)
- [ ] Export CustomCssBundleFactory
- [ ] Export CssBundleFactory (with method to createCombinedCss, createALaCarteCss)
- [ ] Export CustomJsBundleFactory
- [ ] Export JsBundleFactory (with method to createCombinedJs, createALaCarteJs)

**Comment by lynnjepsen** [comment]
We decided we don't need to share webpack config outside of this repository, so closing this issue.
