### ISSUE TITLE
Create a new mdc-top-app-bar

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2222]
- [x] CSS to match the "default" variant
- [x] Includes a navigation icon, with states, by default
- [x] JavaScript will emit an event when that navigation icon is clicked
- [x] Sass mixins to customize the color and shape

**Comment by williamernest** [comment]
Resolved with #2225
