### ISSUE TITLE
Add an mdc-top-app-bar--short variant

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2223]
- [ ] Add CSS to style the short variant
- [ ] Add JavaScript to handle the scroll behavior
- [ ] Include Sass mixins to customize the border radius
