### ISSUE TITLE
Implement non-actionable Standard Image List in a new mdc-image-list

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2314]
- [ ] new Node module: mdc-image-list
- [ ] Document and handle HTML structure for an image-list-item without `<a>`
- [ ] Document and handle HTML structure for text label underneath image
- [ ] Document and handle HTML structure for text label overlaid on top of image
- [ ] Add `mdc-image-list-aspect` mixin for maintaining aspect ratio
- [ ] Add `mdc-image-list-columns` mixin, which styles a Standard Image List to scale its images based on the natural width of the containing element

Follow up PRs will add ripples to the actionable parts of an mdc-image-list
