### ISSUE TITLE
Implement Masonry Image List

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2315]
- [ ] Add `mdc-image-list--masonry`
- [ ] Add `mdc-image-list-masonry-columns`, Styles a Masonry Image List to scale its images based on the container width
- [ ] Update documentation to highlight no need for aspect container element (and indicate that div-instead-of-img is irrelevant)
