### ISSUE TITLE
Create new `mdc-tab` component

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2376]
- [ ] HTML + CSS for a tab with text (`.mdc-tab__text-label`)
- [ ] HTML + CSS for a tab with an icon (`.mdc-tab__icon`)
- [ ] HTML + CSS for a tab with text and an icon
- [ ] `mdc-tab-text-label-color` Sass mixin
- [ ] `mdc-tab-icon-color` Sass mixin
- [ ] Demo of customizing active and inactive state (`.mdc-tab--active`)
- [ ] `MDCTabFoundation` with activate and deactivate methods
- [ ] `MDCTab` vanilla version, with proxy to activate  and deactivate methods
- [ ] Publish new `mdc-tab` Node module

Demo should show a `mdc-tab` activating and deactivating, plus customization

**Comment by kfranqueiro** [comment]
Wait... are we not doing this under `mdc-tabs`?

Naming this module `mdc-tab` would be completely inconsistent with how we decided to name `mdc-chips`, which I thought we intentionally named plural since any use case generally involves multiple of them. Also maybe to avoid having e.g. `packages/mdc-tab/mdc-tab/...` for one of the subcomponents...
