### ISSUE TITLE
Add `mdc-tab__indicator` to `mdc-tab`

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2377]
This uses FLIP to animate the indicator from one tab to another

- [x] HTML + CSS for `mdc-tab__indicator`
- [x] HTML + CSS for `mdc-tab__indicator--icon`
- [x] Add `getIndicatorClientRect` to `MDCTabFoundation`
- [x] Update `activate(previousTabIndicatorClientRect)`
- [x] Update documentation to say there should always be one tab activated (showing indicator)

Demo should show an `mdc-tab__indicator` sliding along a horizontal list of `mdc-tab`

**Comment by patrickrodee** [comment]
Closed in #2565
