### ISSUE TITLE
Add new `mdc-tab-bar`

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2551]
- [ ] Add necessary `getBoundingRect` methods to `MDCTabScroller` and `MDCTab`
- [ ] New HTML and CSS for `mdc-tab-bar`
- [ ] `MDCTabBarFoundation` and `MDCTabBar` should handle tab selection, 
- [ ] `MDCTabBarFoundation` and `MDCTabBar` should have `activateTab` method, which calls `MDCTab.activate`
- [ ] `MDCTabBarFoundation` and `MDCTabBar` should have `slideTabIntoView` method, which calls `MDCTabScroller.slideTo` or `MDCTabScroller.scrollTo` 
- [ ] Update `docs/docsite-tabs.md` to redirect to Tab Bar docs by default
