### ISSUE TITLE
Remove `fr` unit workaround from stylelint config

### ISSUE THREAD

**Issue by sgomes** [material-components/material-components-web#256]
stylelint 7.8.0 has been released, which adds the `fr` unit to the list of known units, removing the need for [our current workaround](https://github.com/material-components/material-components-web/blob/master/.stylelintrc.yaml#L251).

- [ ] update `package.json` to require 7.8.0
- [ ] remove the workaround from `.stylelintrc.yaml`
- [ ] ensure we don't run into any of the deprecations announced in the [7.8.0 release](https://github.com/stylelint/stylelint/releases/tag/7.8.0), refactoring if we do
