### ISSUE TITLE
Implement Snackbar Component

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#28]
Spec Reference: https://www.google.com/design/spec/components/snackbars-toasts.html 

It's been called a "Toast" in the past, but the thing that's not Android-specific is a **snackbar**.
- [x] Initial Implementation
- [x] Dark Theme (background: `#fafafa`, text: text-primary-on-dark, action: theme primary color)
- [x] Keyboard Focus Handling
- [x] In demo, ensure that "Action on Bottom" is unchecked and disabled when "multiline" is unchecked
- [x] End-to-end usage example in README (instantiation, using it in response to an event)
- [x] _Start_-aligned snackbars (left for LTR, right for RTL)
- [x] Add `dismissOnAction` option, which defaults to `true`. When `true`, snackbar dismisses as soon as a user interacts with its action button (see #28).
- [x] Address #564 

> Copied from https://github.com/google/material-design-lite/issues/4490

**Comment by abraham** [comment]
It doesn't look like left-aligned for tablet/desktop is supported or on the todo list. Is that planned?

**Comment by Garbee** [comment]
Left-aligned is new to the spec. A new issue should be made to track adding it as a modifier.

**Comment by traviskaufman** [comment]
THanks @abraham and @Garbee. We actually think it makes the most sense to roll this issue into the TODO list here. Closing #382 and putting as an item.
