### ISSUE TITLE
screenshot:update-goldens should not need to re-run tests

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#2824]
Currently, `screenshot:update-goldens` is basically a superset of `screenshot:test`, which also modifies golden.json based on the test results. This means the current workflow pretty much encourages running the tests twice.

We should do the following so this doesn't need to do that:
* [x] Move golden generation (to a separate file) into `test`, and upload it to GCS
* [x] Repurpose update-goldens to download that golden and overwrite the one in the local checkout (which will then appear in unstaged changes for git)
* [x] Update README/usage since after this the filter options would only be applicable for `screenshot:test`
