### ISSUE TITLE
Update `mdc-switch` to new version in line with Material guidelines

### ISSUE THREAD

**Issue by lynnjepsen** [material-components/material-components-web#2825]
- [ ] new HTML structure, with the thumb and track as sibling elements
- [ ] HTML structure should also have the input element within the thumb, so that focus is within the element with the ripple
- [ ] new JavaScript to listen to the input element, and apply parent CSS classes
- [ ] baseline CSS, which styles the sub-elements based off the parent CSS classes
- [ ] new Sass mixins to cover customizing the color of the thumb and track, in both the toggled on and toggled off state
- [ ] baseline CSS should call these color Sass mixins, and apply color from mdc-theme

We will defer on the disabled state customization, and opacity customization, until a later issue/PR (see #2762 )
