### ISSUE TITLE
Make chip exit on trailing icon interaction optional

### ISSUE THREAD

**Issue by draoncc** [material-components/material-components-web#2869]
## Feature Request

As of 0.35.2, it is not possible to prevent a chip from exiting when the trailing icon is interacted with. In my case, I'd like to remove the chip only after manual confirmation. The `.mdc-chip--exit` class starting the exit sequence of the chip is immediately applied on handling the trailing icon interaction, making it impossible to abort the process unless overwriting the transition values for the class to nothing.

**Comment by kfranqueiro** [comment]
Thanks for logging this issue. This seems like a reasonable feature proposal.

Some technical details of what will need to be done:

* [ ] Chip Foundation: Move `notifyTrailingIconInteraction` and `addClass` calls from `handleTrailingIconInteraction_` to their own public method
* [ ] Chip Foundation: Call new method automatically if a flag is true (default should be true)
* [ ] Chip Component: Create a getter/setter for the new flag

At minimum this can be hooked up through the Chip Set Component via a custom `chipFactory` in order to ensure it is applied to every chip (both those which exist when the set is instantiated, and those added via `addChip`. For example:

```js
const chipSet = new MDCChipSet((el) => {
  const chip = new MDCChip(el);
  chip.shouldRemoveOnTrailingIconClick = false;
  return chip;
});
```

(I'm up for a shorter flag name than that, if we can think of one that's still clear...)

**Comment by bonniezhou** [comment]
`notifyTrailingIconInteraction` should be kept in `handleTrailingIconInteraction_`
