### ISSUE TITLE
Determine and Document Type System and conventions for writing closure code

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#326]
This is the "first" story within the Closure Compiler milestone. The goal of this story is to provide a foundation so that ourselves and contributors can build out closure annotations with a solid set of conventions.

- [x] Evaluate general approach taken in https://github.com/material-components/material-components-web/tree/experimental/closure-research (see `mdc-icon-toggle` and all dependents)
- [x] Debate and solidify all parts of the approach including:
  - Type heirarchy
  - File structure
  - Naming Conventions
- [x] Verify our approach by running ad-hoc tests on closurized code in `experimental/closure-research` branch: build the mdc-icon-toggle JS, build simple js entry point for closure to put on icon-toggle demo page, swap out mdc-web with that closure entry point. _Ensure that within that entry point, icon toggle API is being programatically accessed_.
- [ ] Create `docs/closure-compiler.md` detailing all of these conventions

---

## Preliminary Brainstorm on Conventions

- Attempt to make MDCComponent `@abstract` ~_(RESEARCH)_~
  - Follow-up: Can be done by removing the default `attachTo()` method, which we could document in code, in writing, and potentially write linter rules for.
- Investigate making MDCFoundation `@abstract` ~_(RESEARCH)_~
  - Follow-up: Can be done.
- Preserve type heirarchy from experimental branch
  - Adapters are `{!Object}` types
  - `MDCFoundation` parameterized by its adapter
    
  ```js
       /** @final @extends MDCFoundation<!MDCFooAdapter> */
       class MDCFooFoundation extends MDCFoundation { /* ... */ }
   ```
  -   `MDCComponent` parameterized by its foundation
    
  ```js
       /** @final @extends MDCComponent<!MDCFooFoundation> */
       class MDCFoo extends MDCComponent { /* ... */ }
   ```

- `@typedefs` are always `let` declarations, always pascal case, and always end in `Type`.
  ```js
  /** 
   * @typedef {{foo: string, bar: number}}
   */
  let EventDataType;
  ```

- All foundation/component classes that extend from `MDCBase` and are not meant to be extended _must be marked `@final`_. This will prevent unintended subclassing which would lead to easily-breakable client code.

- Objects that use event names or other external symbols as keys _must_ be declared as `@dict`

  ```js
  /** @dict */
  const activationDeactivationPairs = {
    'mousedown': 'mouseup',
    'touchstart': 'touchend',
  };
  ```
- Adapters always declared as `@record` objects
- File structure:
    - adapter.js for adapter
    - foundation.js for foundation 
    - index.js for component
- Eslint-disable for unused var warnings / unused import warnings when it comes to @typedefs, @record imports, etc.
    - Crude
    - Use ignore patterns instead
        - http://eslint.org/docs/rules/no-unused-vars 
        - Anything matching “MDC\<PascalCase\>Adapter” _(CONVENTION)_
        - Anything matching “\<PascalCase\>Type” _(CONVENTION)_
- All getter/setter properties need to be specified in the constructor
  - _EDIT_: This may not be the case anymore, see [below comment](https://github.com/material-components/material-components-web/issues/326#issuecomment-283769462)
- `--jscomp_off accessControls` :(
  - https://github.com/google/closure-compiler/issues/2261 
  - Short-term we disable
  - We should work with closure team and fix
- No using re-exported modules
  - BAD: `import {MDCFoundation} from ‘@material/base’`;
  - GOOD: `import MDCFoundation from ‘@material/base/foundation’`;

- `cssClasses` / `strings` / `numbers` are defined in `constants.js` (and transitively in `foundation.js`) as follows:
  - `cssClasses` => `/** @enum {string} */`
  - `strings` => `/** @enum {string} */`
  - `numbers` => `/** @enum {number} */`

**Comment by shyndman** [comment]
> Attempt to make MDCComponent @abstract (RESEARCH)
What is the research hoping to uncover?

> All getter/setter properties need to be specified in the constructor
Do you have an example of this?

**Comment by traviskaufman** [comment]
@shyndman 

> What is the research hoping to uncover?

We want to see whether or not it makes sense to make `MDCFoundation` and `MDCComponent` abstract classes, rather than concrete classes. We'd have to make some changes to their APIs, particularly in regards to static methods. I ran into a few issues (which I currently can't remember :p) while prototyping and attempting to do this, and I quickly scrapped it since I wanted to focus on other parts of closure integration. However, we want to revisit it. Having the compile-time safety of making sure `getDefaultFoundation()` is defined, rather than throwing an error as its default implementation, is a much better solve.

> Do you have an example of this?

- https://github.com/material-components/material-components-web/blob/experimental/closure-research/packages/mdc-ripple/index.js#L74-L75
- https://github.com/material-components/material-components-web/blob/experimental/closure-research/packages/mdc-icon-toggle/index.js#L46-L53

All of those property expressions are defined as getters/setters within the code. However, if you try to reference them using property access without having those property expressions, closure will complain.

...that being said when I just tried it with [this code](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520ADVANCED_OPTIMIZATIONS%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%2540formatting%2520pretty_print%250A%252F%252F%2520%2540language_out%2520ECMASCRIPT5%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250A%252F%252F%2520ADD%2520YOUR%2520CODE%2520HERE%250Aclass%2520Foo%2520%257B%250A%2520%2520constructor()%2520%257B%250A%2520%2520%2520%2520%252F**%2520%2540private%2520%257Bstring%257D%2520*%252F%250A%2520%2520%2520%2520this.bar_%2520%253D%2520''%253B%250A%2520%2520%257D%250A%2520%2520%250A%2520%2520%252F**%250A%2520%2520%2520*%2520%2540return%2520%257Bstring%257D%250A%2520%2520%2520*%252F%250A%2520%2520get%2520bar()%2520%257B%250A%2520%2520%2520%2520return%2520this.bar_%253B%250A%2520%2520%257D%250A%2520%2520%250A%2520%2520%252F**%250A%2520%2520%2520*%2520%2540param%2520%257Bstring%257D%2520bar%250A%2520%2520%2520*%252F%250A%2520%2509set%2520bar(bar)%2520%257B%250A%2520%2520%2520%2520this.bar_%2520%253D%2520bar%253B%250A%2520%2520%257D%250A%257D%250A%250Aconst%2520f%2520%253D%2520new%2520Foo()%253B%250Af.bar%2520%253D%2520'hello'%253B%250Aconsole.log(f.bar)%253B) it seemed fine, so maybe this problem has been solved upstream.

**Comment by shyndman** [comment]
Gotcha. Thanks.

**Comment by traviskaufman** [comment]
Pushed changes on `experimental/closure-research` which adds a build test to verify things working correctly. So far so good it seems.

<img width="1440" alt="screen shot 2017-03-24 at 17 44 07" src="https://cloud.githubusercontent.com/assets/1185269/24314740/96178196-10b9-11e7-9d9e-d00353ac67cf.png">
