### ISSUE TITLE
Create build test infrastructure to verify compilation of closurized code

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#327]
- [x] Create a mechanism for "whitelisting" packages that need to be tested by the closure compiler, perhaps as a key in `package.json`:

```
"closure-whitelist": [
  "mdc-icon-toggle",
  "mdc-ripple",
  ...
]
```

Eventually once everything is compilable, this mechanism can be removed.

- [x] Write script to type-check (compile without emitting) all closurized packages. This script should be integrated, in some way, into `npm test`, perhaps as `posttest`.
- [x] Configure TravisCI to be able to run build tests (Java 8)
- [x] Add section to `authoring-components.md` where we reference `closure-compiler.md` which details how we build and test all of our closure code.

**Comment by traviskaufman** [comment]
FYI https://github.com/google/closure-compiler/issues/2386
