### ISSUE TITLE
mdc-tab, mdc-tab-bar: Update icon usage in READMEs

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#3282]
* [x] Use `material-icons` and reference a valid icon (e.g. `favorite` instead of `heart`) (#3390, #3391)
* [ ] Document inclusion of Material Icons consistently with #3266 once that's settled and merged
* [ ] Add `aria-hidden="true"` to icons in examples where Material Icons are accompanied by text labels
