### ISSUE TITLE
Dialog auto-stacking doesn't account for reversed button order

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#3561]
The [Dialog article](https://material.io/design/components/dialogs.html#anatomy) indicates that when buttons are stacked, confirming actions are above (before) dismissive actions, but when buttons are not stacked, confirming actions are after dismissive actions.

The new Dialog code in #3413 automatically stacks buttons if there isn't enough space to fit them side-by-side, but this code isn't accounting for the fact that the buttons end up effectively reversed. Moreover, we shouldn't rely on flexbox reverse ordering for this, since that doesn't reverse tab order.

I envision the following steps to resolve this:

* [ ] Whenever the component automatically switches between stacked and non-stacked, reverse the order of elements in the actions region of the dialog via JS (so that the tab order also switches)
* [ ] Allow disabling auto-stacking behavior via a component property / foundation method (in case anyone has more complicated button arrangements that make this awkward)
* [ ] Detect if `--stacked` is already applied during `initialSyncWithDOM`, and automatically disable auto-stacking if so
