### ISSUE TITLE
Implement "FAB-toolbar" component

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#36]
- Spec reference: https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions
- Motion video mock: https://material-design.storage.googleapis.com/publish/material_v_8/material_ext_publish/0B8v7jImPsDi-NXNEaXZ0Um1yc0k/components-buttons-fab-transition_toolbar_01.webm
- [ ] X & Y positions that FAB moves to needs clarification
- [ ] Implement Bottom FAB menu component
- [ ] Implement Proper transitions between FAB and Toolbar

There are internal motion mocks for these transitions that I can get when it comes time to implement.

> Copied from https://github.com/google/material-design-lite/issues/4482
