### ISSUE TITLE
Implement Toolbar Component

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#38]
- [x] No-Seam / Static
- [x] Seam Always / Fixed

---
- [x] No-Seam -> Seam + Fixed / Waterfall
- [x] Flexible Header

Spec reference: https://www.google.com/design/spec/components/toolbars.html

> Copied from https://github.com/google/material-design-lite/issues/4480

**Comment by yeelan0319** [comment]
Here is the prototype of toolbar:

Supported features:
- Fixed to top with 4 elevation
- RTL
- Theme on dark and light

[CodePen Link](http://codepen.io/yeelan0319/pen/XpEbby)

**Comment by traviskaufman** [comment]
@yeelan0319 nice work so far! Some initial thoughts on the prototype:

- Noticed that the `<body>` styles have padding applied to it. This looks like it would only be an issue when there is a _fixed_ toolbar. Furthermore, I'm not sure we'd want that to be padding, we may want to use `margin` instead, and alter `margin-top` only. Finally, we probably don't want to do this by default. What if instead we created a css class `mdc-toolbar-adjust` that could be put onto the body (or any other element) and bump it's margin top. E.g.

```scss
$mdc-toolbar-height: 64px !default;

.mdc-toolbar-adjust {
  margin-top: $mdc-toolbar-height;
}

.mdc-toolbar {
  height: $mdc-toolbar-height;
}
```

```html
<body class="mdc-toolbar-adjust">
  <div class="mdc-toolbar mdc-toolbar--fixed">
    <!-- ... -->
  </div>
  <!-- main content -->
</body>
```

- I'm not sure if the toolbar should be a `<nav>`, or have a `role="toolbar"`. I think here the use of the word _toolbar_ just refers to the stylistic treatment of the element within the material system, but it doesn't necessarily have to be used as a toolbar. @amsheehan @sgomes thoughts?

- Regarding whether or not there is a default font size for toolbar, spec doesn't say but I'd probably check with design

- It may be useful to split the toolbar into two sections using something like flexbox, e.g. the "start" side which may contain a site title / logo, and an "end" side which may contain some icon buttons, etc. e.g. similar to Inbox. However, we also may just want to leave that up to the individual developers and just worry about styling the outer toolbar itself.

**Comment by Garbee** [comment]
Aria [toolbar](https://www.w3.org/TR/wai-aria/roles#toolbar):

> A collection of commonly used function buttons or controls represented in compact visual form.

The toolbar container should not have the role. However, any inner actions container with icons for doing tasks should be encouraged to have the role.

+1 to flexbox, it also will handle RTL transitions seamlessly.

Do remember toolbars are not app-level only, but can be contained within inner nodes as well.

**Comment by traviskaufman** [comment]
@yeelan0319 regarding having flex containers, here's a codepen example http://codepen.io/traviskaufman/pen/YNLRVN

**Comment by yeelan0319** [comment]
- @traviskaufman @Garbee Valid thoughts on semantic tag and role. If toolbar is considered more as a style instead of functional component, we should remove the role and make it a div. 
- Text style on toolbar is listed under [Typography](https://material.io/guidelines/style/typography.html) section in spec, which is `App bar: Title style, Medium 20sp`. I will put this into `mdc-toolbar__title`.
- The flex container idea is pretty interesting. So I will put `mdc-toolbar__section-start` and `mdc-toolbar__section-end` as container for user to put their items in.

**Comment by Garbee** [comment]
The use of multiple rows will also need to be thought through as well. Just remembered application-level bars can have I think up to 3 rows in different contexts. That should be integrated close to the start of the component because handling that could affect how the structure of the general toolbar will be done.

**Comment by traviskaufman** [comment]
> The use of multiple rows will also need to be thought through as well.

I don't think this isn't a requirement for toolbars; [the spec](https://material.io/guidelines/components/toolbars.html#) makes no mention of it. You may be thinking of something like [system bars](https://material.io/guidelines/layout/structure.html#structure-system-bars), which are layered on top of toolbars and not something we support.

**Comment by Garbee** [comment]
In Appbar metrics:

> The app bar with significantly increased height for prominence. (Height 128dp)

![appbar](https://storage.googleapis.com/material-design/publish/material_v_10/assets/0B6Okdz75tqQsSDBhX3BwSURRc1U/layout_structure_appbar_metrics3.png)

**Comment by yeelan0319** [comment]
Merged to master with commit #267

**Comment by yeelan0319** [comment]
Start working on implementing flexible header:

Here is a [prototype of flexible header on CodePen](http://codepen.io/yeelan0319/pen/dvVzzm).

Parking lot:
1.  Should we call the whole thing appbar or toolbar. There I saw the definition in [Scrolling techniques](https://material.io/guidelines/patterns/scrolling-techniques.html#scrolling-techniques-behavior) talking about the whole thing as appbar.
2. How generic the flexible header should be? Will it be applicable to things other than toolbar

**Comment by Garbee** [comment]
Appbar is toolbar for the page layout. So it gets extra stuff possible that
isn't recommended in the regular in page toolbars.

I'd say the flexible bit is appbar level only. I don't recall any parts of
the specification doing the same type of thing within any component other
than layout.

**Comment by yeelan0319** [comment]
Thanks @Garbee 

I also confirmed with our designer that the flexible behavior is only applicable to appbar.

I will follow up with the discussion about appbar-toolbar relationship today. The tricky part is toolbar need to remove its theme (obviously should have no shadow casting).

My current thinking is 
```
<div class="mdc-appbar">
  <div class="mdc-toolbar no-theme">...</div>
  <div class="mdc-flexible-space"></div>
</div>
```
Or another possibility I could explore is using `:after` for mdc-toolbar, like:
```
<style>
  .mdc-toolbar--with-flexible-space :after {
    // flexible header definition here
  }
</style>
<div class="mdc-toolbar mdc-toolbar--with-flexible-space">...</div>
```

**Comment by traviskaufman** [comment]
Thanks @yeelan0319 

After discussing with team, the plan is to go with **modifier classes on mdc-toolbar**, for both seams and flexible header. As @yeelan0319, design team confirmed that flexible headers / seams are coupled to toolbars, so it makes sense to bake them into it directly, rather than having to educate users on how to use another component in a certain way.

**Comment by yeelan0319** [comment]
@material-components/mdc-web MDC-Web Eng Outline: Flexible Header: https://docs.google.com/document/d/1NpiWO-2A-74wYcl0FW_tZ2JU4kNBjmxhaxqJ26rFm2M/edit#heading=h.3qa3hj2cqohb

**Comment by traviskaufman** [comment]
Closed via #499
