### ISSUE TITLE
Allow finer-grained control of emitted CSS

### ISSUE THREAD

**Issue by kfranqueiro** [material-components/material-components-web#4227]
In the past, we've received requests (such as #3357) for ways to better control what CSS is output by MDC Web. Being able to more granularly control what CSS we output also has the potential to help prospective framework wrappers that also want to govern output styles.

To this end, @mmalerba has worked on a prototype which would allow selectively including MDC Web's styles either all at once or piece-by-piece, with the ability to request the following subsets:

* base ("structure") - anything that doesn't fall into one of the more specific subsets
* mdc-theme-dependent ("color")
* typography
* animation

Miles' POC, along with a bit of fine-tuning and infrastructure work, is in #4228.

The end result of this is that existing usage of MDC Web will behave exactly the same - no existing mixin APIs change, nor does the output CSS if you continue to import `@material/foo/mdc-foo`. But you will also have the option of `@include mdc-foo(...)` and specifying a query of one or more subsets of the component's styles.

Since these changes are intended to be fully backwards-compatible, we can merge these PRs to master one by one. We should also be able to check CSS output on master vs. on the branch and verify that the results are the same (run `npm run build` on each one and move the folder somewhere to be diffed afterwards).

The following components have emitted styles that will need to be converted:

* [x] mdc-button (@mmalerba + @kfranqueiro, #4228)
* [x] mdc-checkbox (@mmalerba, #4258)
* [x] mdc-ripple (partially in #4228; emitted styles in #4383)
* [x] mdc-menu-surface (@crisbeto, #4279)
* [x] mdc-menu (@crisbeto, #4278)
* [x] mdc-radio (@mmalerba, #4270)
* [x] mdc-switch (@crisbeto, #4275)
* [x] mdc-card (@mmalerba, #4301)
* [x] mdc-typography (mixins done by @mmalerba in #4305; all emitted styles covered via mixins)
* [x] mdc-elevation (mixins done by @mmalerba in #4308; emitted styles in #4383)
* [x] mdc-theme (`mdc-theme-prop` not accepting `$query` on purpose; emitted styles in #4383)
* [x] mdc-shape (mixins only; @mmalerba, #4384)
* [x] mdc-form-field (@mmalerba, #4521)
* [x] mdc-dialog (@kfranqueiro, #4524)
* [x] mdc-fab (@kfranqueiro, #4526)
* [x] mdc-grid-list (@kfranqueiro, #4534)
* [x] mdc-image-list (@kfranqueiro, #4535)
* [x] mdc-icon-button (@kfranqueiro, #4536)
* [x] mdc-chips (@mmalerba, #4693)
* [x] mdc-drawer (@crisbeto, #4877)
* [ ] mdc-layout-grid
* [x] mdc-linear-progress (@crisbeto, #4898)
* [ ] mdc-list
* [x] mdc-slider (@crisbeto, #4871)
* [x] mdc-snackbar (@crisbeto, #4876)
* [x] mdc-tab-indicator (@crisbeto, #4838)
* [x] mdc-tab (@crisbeto, #4838)
* [x] mdc-tab-scroller (@crisbeto, #4838)
* [x] mdc-tab-bar (@crisbeto, #4838)
* [ ] mdc-top-app-bar

As with #4225, it may be best to leave textfield-related things until last:

* [ ] mdc-floating-label
* [ ] mdc-notched-outline
* [ ] mdc-line-ripple
* [ ] mdc-select
* [ ] mdc-textfield

Bear in mind that some of these may have cross-dependencies, which will require at least partial conversions of other packages as well, so I've attempted to front-load any likely dependencies as possible (I think ripple is really the main one, and that's already been largely tackled as far as it needs to be for other components to use it). The first PR converts button fully, and ripple partially (mostly).

We should skip the following since they're deprecated (and likely to be removed as part of #4225):

* mdc-icon-toggle
* mdc-tabs
* mdc-toolbar

**Comment by nemethmik** [comment]
I have spent a week or so on evaluating the possibility to apply MDC Web directly or MDC React in my mobile-first application. My impression is that because of this excessive use of SCSS the entire MDC Web is an implementation of MD mainly for static websites. It is not really OK for highly dynamic mobile applications, because the nature of SCSS. For example, to define the colors, themes or the number of columns for an image list in MDC Web, you can do that only fiddling with SCSS. This is really unacceptable for mobile app development. I think framework should hide the intricacies of SCSS/CSS. So, my question is that are you planning to replace SCSS with a more flexible, runtime, dynamic styling technology? Is this the reason you have ejected thee MDC Web components?

**Comment by jasonkylefrank** [comment]
To expand on what @nemethmik brought up, I'm curious if your team has considered using a CSS-in-JS approach for styles (e.g., JSS)?  If not for MDC-Web, what about for MDC-Web-React (e.g., Styled Components)?  

I'm starting to get the feeling that SASS may not be the strongest overall styling approach these days (and could address some of the points that @nemethmik brought up), but I'd like to hear your thoughts.
