### ISSUE TITLE
Implement MVP of Datatable component

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#4591]
Implement MVP of datatable component:

- [x] Add base styles for standard variant. Implement sass mixins for customizations. Screenshot test with base styles. (PR #4600)
- [x] Implement interactions and new event to select / deselect table rows. Screenshot test with row selection. (PR #4662)
- [x] Update docs. (PR #4694)
- [ ] Update catalog.

Spec reference: http://material.io/go/design-data-tables

**Comment by fopsdev** [comment]
Just curious when this will land?

**Comment by moog16** [comment]
There is a PR open to merge into master right now.
