### ISSUE TITLE
Investigate a solution to all stacking related issues

### ISSUE THREAD

**Issue by amsheehan** [material-components/material-components-web#461]
Over the course of the project, MDC Web has received several pull requests to solve stacking issues in different components and contexts. This was acceptable for the number of components in the wild, but as our code base grows, so does the number of z-index issues we're seeing. It is now time to find a more holistic approach to stacking.

Investigate a solution to this issue that can be accessed and applied globally to any component such that stacking order reflects elevation specifications and doesn't collide with logical expectations of how components should behave (ie: radio buttons should not stack on top of selects).

### Possible Solutions:

- [ ] SASS mixin that takes an elevation as defined by spec and sets correct z-index
- [ ] SASS list, whose items correspond to a floor, the specified elevations, and a ceiling
- [ ] SASS file declaring z-index rules for all components

**Comment by amsheehan** [comment]
## Initial Solution - Solicitation of Feedback

As our component library grows, we have found that `z-index` gets set fairly arbitrarily, and has resulted in some stacking issues when using certain combinations of components, e.g.: `mdc-button` showing through `mdc-simple-menu` (#432)

One option is creating a file somewhere that references classnames from all of our components specifically for setting `z-index` rules:

`@material/mdc-z-index-library.scss` (or whatever)
```css
.mdc-simple-menu {
  .mdc-list-item {
    z-index: 1;
  }
}

.mdc-dialog {
  &__surface {
    z-index: 4;
  }
}
```
This is problematic as it breaks with our convention of packages being self-contained, co-located `.js`, `.scss`, `.json`, and `.md` files; and duplicating selectors for the purposes of organization is a mess to maintain.

Another option is to create a manifest of variables that correspond to the class they will be used with:

`_z-index-variables.scss`
```css
$z-index-something: 400,
$z-index-something-else: 600
```

```css
@import "z-index-variables";

.mdc-something {
  z-index: $z-index-something;
}

.mdc-something-else {
  z-index: $z-index-something-else;
}
```

While this creates a single source of truth for the values of z-indices across MDC Web (much easier to maintain), I think we can do better. 

I think the best solution is to add a mixin to the `mdc-elevation` component called `mdc-stacking-level()`. This mixin takes a `$z-value` much like the `mdc-elevation()` mixin and uses a map to set the `z-index` of an element to the corresponding `$z-value` * 100.

`mdc-elevation()`, which also takes a `$z-value`, will be modified to set the `z-index` of an element as well, based on the same stacking map. This makes implementation such that the user: 
1. Only needs to set `mdc-elevation()` in most cases
1. Use `mdc-stacking-level()` for safer z-indices when `mdc-elevation()` isn't desired
1. Override `mdc-elevation()` with `mdc-stacking-level()` in special cases (so far only `mdc-simple-menu.scss` requires this)

`mdc-stacking-level()` also takes two special arguments called `behind` and `max`. `behind` is used when the user would like to set the `z-index` to -1, and `max` is when the user would like the element to have the highest possible `z-index` available in MDC Web.

Finally, we multiply each `z-index` value by 100 to provide ample "space" between our predefined z-indices. This way if a user would like to place any elements in between `MDC Web` components in the stacking order, they may.

### The Downside

Any component that wants to set a `z-index` will have to depend on `mdc-elevation`, even if a shadow simulating elevation isn't required. 😦 

```css
@import "@material/elevation/mixins";

...

.mdc-does-not-have-shadow {
  @include mdc-stacking-level(3) // requires mdc-elevation
}
```

### The Upside

Any component that sets a `z-index` will depend on `mdc-elevation` 😄 

This, I believe, is a good compromise with the users of MDC Web. It forces them to think about how they use z-index, which makes setting the value less arbitrary. A more strict system will result in fewer bugs like the one mentioned above, which I believe outweighs the negative of adding a 100 line dependency.

Any feedback is welcome!

**Comment by traviskaufman** [comment]
This is an excellent summary @amsheehan ! 👍 to incorporating z-index into mdc-elevation. I think it only makes sense; if a piece of material in real life has a higher elevation than another piece of material, it would cover it. 

Only thing I'd think about here is what happens when a component's elevation changes? E.g. buttons when they go `:active`?

**Comment by amsheehan** [comment]
I actually don't see where that concept will effect z-indeces. Currently, the `:active` pseudo selector doesn't apply any changes to a component's z-index where `mdc-elevation` is used.

Now, if that's a behavior we would like to incorporate, we certainly could. The only prerequisite would be this: Given two elements that can "trade" elevations and cover one another, a singular stacking context would be required, e.g.:

```html
<div>
  <div class="left-card">sample 1</div>
  <div class="right-card">sample 2</div>
</div>
```

In this example, `left-card` and `right-card` are in the same stacking context, and therefore would be able to swap both perceived elevation (box-shadow, scale), and actual elevation (z-index). This would not be the case if they were in _different_ stacking contexts, unless the context itself changed elevations using z-index, e.g.:

```html
<div class="context-one">
  <div class="left-card">sample 1</div>
  <div class="some-other-card">arbitrary card</div>
</div>
<div class="context-two">
  <div class="right-card">sample 2</div>
</div>
```
In this example, changing the `z-index` of either `left-card` or `right-card` would not necessarily cause them to toggle which element is higher in the stacking order.

At any rate, this would be an enhancement to the _behavior_ of pieces of Material [sic] and would probably deserve some input from product and design. What I propose is we move forward with this solution initially and if we would like to solve for this, we at least have a very organized foundation to start from; one that tackles the challenges we currently face with arbitrary z-index assignments.

**Comment by louie-mogul** [comment]
Sorry to post on a closed topic, but I think just changing z-index in some cases won't be enough, especially if the simple-menu is enclosed within an object with overflow hidden, in which case it fails even with a high z-index. The solution would be to incorporate 'position:fixed' and the z-index, and position with JS to bypass any encapsulation.
