### ISSUE TITLE
Clean up: demos/deprecated packages

### ISSUE THREAD

**Issue by moog16** [material-components/material-components-web#4738]
- [x] Remove demos
  - [x] Remove package deps for demos
- [x] Remove deprecated packages
   - [x] tabs
   - [x] ~~icon toggle~~ # already removed
   - [x] toolbar

**Comment by moog16** [comment]
waiting for https://github.com/material-components/material-components-web/pull/4752 before moving ahead with remove tabs, icontoggle, toolbar.

**Comment by moog16** [comment]
Once https://github.com/material-components/material-components-web/pull/4687 is merged, this can be closed.

**Comment by abhiomkar** [comment]
Toolbar is removed, we can close this once #4784 is merged.

**Comment by moog16** [comment]
All deprecated packages removed!
