### ISSUE TITLE
Density Subsystem

### ISSUE THREAD

**Issue by abhiomkar** [material-components/material-components-web#4820]
Epic bug to track all the things related to Density Subsystem.

### Set 1

- [x] Button
- [x] Icon Button
- [x] Chips
- [ ] ~Fab~ (Not applicable)

### Set 2

- [ ] ~Select~ (Select is being refactored, will add density later)
- [x] Text Field

### Set 3

- [x] Data Table
- [x] List / Menu

### Set 4

- [x] Tab Bar
- [ ] ~Top App Bar~ (Out of scope of this release)
- [ ] ~Snackbar~ (Not applicable)

### Set 5

- [x] Checkbox
- [x] Radio
- [x] Switch

### Center align items

To support dynamic height of component inner elements of a component needs to be always center aligned.

* Use flexbox to center align for simple cases.
* If inner element is absolutely positioned (for example, text field icon), use top and transform CSS properties to center align (Compatible with all browsers including IE 11).
* If the component is nested set height to the child block element to include children padding in CSS box sizing. For example, set height to Tab when density is applied to Tab Bar.

### Height / size mixin

Introduce a Height or size (In case of checkbox, radio, etc) mixin to customize the visual height of a component to any pixels without any boundary or height validation. This mixin also adjusts the inner element structure to support dynamic height of component.

### Density mixin

Density mixin mostly encapsulates setting the component height and also adjusting the touch target to match with visual height. Density mixin also does sass param input validation.

Here are some of the important flags defined per component:

```scss
$mdc-foo-height: 36px !default;
$mdc-foo-minimum-height: 24px !default;
$mdc-foo-maximum-height: $mdc-foo-height !default;
$mdc-foo-density-default-scale: $mdc-density-default-scale !default;
$mdc-foo-density-config: (
  height: (
    default: $mdc-foo-height,
    maximum: $mdc-foo-maximum-height,
    minimum: $mdc-foo-minimum-height,
  ),
) !default;
```

Each component maintains `default`, `minimum` and `maximum` height or size information for validation via `mdc-density-prop-value($density-config, $density-scale, $property-name)` function defined in `@material/density` package.

### Revert touch target styles

Density mixin also reverts any touch target related styles to adjust the touch target height / size with visual component height. Create a separate mixin to revert these styles to separate the concerns.

### Remove `--dense` variant

Remove outdated `--dense` variants and related styles, docs, screenshots from component.

### Screenshot tests

Add a screenshot tests in `spec/mdc-foo/mixins/density.html` path.

**Comment by abhiomkar** [comment]
Density mixins are added to above components. Needs more docs and demos for usage / examples.

**Comment by abhiomkar** [comment]
Density subsystem is released in v4.0.0. Closing this issue.
