### ISSUE TITLE
Implement Text Field Boxes

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#673]
Note: This does _not_ cover the new UX interaction states for text fields in general. That is covered by a separate issue.

- [x] Add a `mdc-textfield--box` class which provides the boxed background for a textfield, and alters any baselines that need to be alter
- [x] Implement the ripple treatments for text field boxes.
- [x] Ensure text field box dark mode treatments are in place
- [x] Ensure dense mode treatments are in place
- [x] Ensure text field boxes work within an RTL context
- [x] Ensure text field box can gracefully degrade
