### ISSUE TITLE
Implement updated UX states for text fields

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#675]
- [x] Move `mdc-textfield__bottom-line` out of `mdc-textfield--box` scope and put within the general `mdc-textfield` scope, replacing any `::after` style rules with `.mdc-textfield__bottom-line` style rules
- [x] Idle
- [x] Hover
- [x] Focus ("Press" in spec)
- [x] Invalid ("Error" in spec)
- [x] Ensure textfield can gracefully degrade to CSS-Only
- [x] Ensure all states work for dark mode

_Breaking change_: The underline for `mdc-textfield`s will need to be graduated to a DOM element
