### ISSUE TITLE
Implement UX changes for`mdc-textarea`

### ISSUE THREAD

**Issue by traviskaufman** [material-components/material-components-web#676]
- [ ] Convert `mdc-textfield--multiline` into `mdc-textarea` (_BREAKING CHANGE_)
- [ ] Idle
- [ ] Hover
- [ ] Focus ("press" in spec)
- [ ] Invalid ("error" in spec)
- [ ] Ensure that translucent text treatment shown in spec textarea mock when text overflows is documented as an _example_ stylistic treatment which is not supposed to be used on the web platform.
