### ISSUE TITLE
Proposal: Document Javascript requirements across components

### ISSUE THREAD

**Issue by Whiteseeker** [material-components/material-components-web#740]
# Documentation Request
It would be great in the doc to have a list of component that require javascript and a list of component that doesn't require javascript, and maybe a list for when javascript is optional.
I'm developing a website javascript-less ([here](http://www.opengl-tutorials.com)) and I'm unsure what I can/can't use from MDC web.

PS: I know I have google analytics in the website -_- But apart from that I try not to use javascript to reduce loading time.

**Comment by traviskaufman** [comment]
I think this is a really good idea. However, I don't want to add another place where things could quickly go out of date. Furthermore, I don't want to add yet another task for contributors to complete before they can ship a component. A viable solution here might be:

- [ ] Add a `javascript` "enum" to the front matter of our READMEs which could either be `NONE`, `OPTIONAL`, or `REQUIRED`.
- [ ] Create a script which can generate/updated a table within the top-level README of components and whether or not they contain/require JS. This table should have a comment above it explicitly saying it's generated automatically
- [ ] Update `./scripts/post-release.sh` to run this script as part of our release process.

**Comment by traviskaufman** [comment]
@material-components/mdc-web WDYT?

**Comment by Whiteseeker** [comment]
I like that idea (^_^) can't wait to see that table :P

**Comment by Garbee** [comment]
I think the enumerated field and auto-generate any user-friendly views from that is a great idea. It would also allow an indicator to be displayed on the pages of the doc site as well later on.

**Comment by traviskaufman** [comment]
👍 I'll leave this open for one more week for people to add their thoughts, and if this consensus still sounds good by then I'll add it to our tracker.
