### ISSUE TITLE
Investigate how toolbar actions should show focus/active state

### ISSUE THREAD

**Issue by Garbee** [material-components/material-components-web#993]
The toolbar icons currently only have the basic outline for focus/active state. This doesn't mesh well with what the rest of MD components provide. I think it would be best as a starting point to handle the toolbar icons/actions as buttons for state. So we'd copy the same background color changes for active, focus/hover, disabled, etc. states. This will improve the design to fit far better with the MD spec and improve the usability and a11y of the component for users.

The current spec doesn't provide any guidance here. Which is why copying buttons as a baseline is my recommendation.

**Comment by yeelan0319** [comment]
@Garbee Our designers agreed with what you suggested here. We also checked implementations on mobile platforms that they have ripple applied when pressed. 

In this case, it totally make sense to make if we change those icons to be icon buttons. The thing that we should do here is:
- [ ] Change toolbar icon to use be a button 
- [ ] Enable ripple on those buttons
- [ ] Update the README and document

See if you agree with those changes.

**Comment by Garbee** [comment]
Yup, SGTM. Just to be clear though:

> Change toolbar icon to use be a button

I infer this as, "refactor them to be button nodes and style appropriately to emulate buttons." As actually re-using `mdc-button` itself will be tricky due to the sizing. Unless a modifier is added to convert them into toolbar buttons easily enough.

**Comment by yeelan0319** [comment]
Good catch @Garbee

You are right that we don't really want to use an `mdc-button` in this context.

**Comment by williamernest** [comment]
Closed by #2138 by adding icon ripples to action items. Toolbar has also been deprecated. It's replacement, Top App Bar, already handles the focus/pressed/selected state of icons.
